### ISSUE TITLE
[0.6.5-beta.3] Access to author.airpair for GitHub account [20169657:tatmanblue] by request to team@airpair.com

### ISSUE THREAD

**Issue by tatmanblue** [airpair/author.airpair.com#11]

**Comment by jkresner** [comment]
Surprised you have the audacity.

**Comment by tatmanblue** [comment]
sorry I do not understand what that means.   I not sure what any of it means.  Some clarification would be nice.

**Comment by jkresner** [comment]
How many times have you visited airpair in the last few months?

**Comment by tatmanblue** [comment]
I joined today.  I was trying to comment on a great article I read.  I got these "errors" with little explanation as to what they meant.

**Comment by jkresner** [comment]
Are you reading the articles from a big office? I'm trying to reconcile some data. Thank you for your patience.

**Comment by tatmanblue** [comment]
yes

**Comment by luciano-renzi** [comment]
> Surprised you have the audacity.

Wow, good job mate. Having the same error here. Won't even bother seeing how friendly support is
