### ISSUE TITLE
SUBMIT screen hangs when creating Github repo

### ISSUE THREAD

**Issue by ptmcg** [airpair/author.airpair.com#2]
I have prepared a tutorial article on Pyparsing, and have added tags and supporting info. However, I seem to be stuck when trying to SUBMIT this article.  I have attached a screenshot at the point at which I am stuck. I have tried with Firefox, Chrome, and Microsoft Edge, all with the same result.

The problem seems to be in the creation of my github repo, as I never get a response that the article slug is no longer available.

The URL is https://author.airpair.com/submit/54ff547ae02a350c00dab9a8.
![airpair_screenshot2](https://cloud.githubusercontent.com/assets/383875/12584766/a34e8754-c40e-11e5-9c85-b5fb8b90c222.jpg)

**Comment by jkresner** [comment]
Another rather large update coming in the next few hours.

On Tuesday, January 26, 2016, Paul McGuire notifications@github.com wrote:

> I have prepared a tutorial article on Pyparsing, and have added tags and
> supporting info However, I seem to be stuck when trying to SUBMIT this
> article I have attached a screenshot at the point at which I am stuck I
> have tried with Firefox, Chrome, and Microsoft Edge, all with the same
> result
> 
> The problem seems to be in the creation of my github repo, as I never get
> a response that the article slug is no longer available
> 
> The URL is https://authorairpaircom/submit/54ff547ae02a350c00dab9a8
> [image: airpair_screenshot2]
> https://camo.githubusercontent.com/ae340c43fabb35c584bc62e2966fb3dc2ec063ce/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f3338333837352f31323538343736362f61333465383735342d633430652d313165352d396338352d6235666238623930633232326a7067
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/author.airpair.com/issues/2.

## 

_Jonathon Kresner_
_Co-founder, CEO_
@AirPair http://twitter.com/airpair | _airpair.com
http://www.airpair.com_
@hackerpreneur http://twitter.com/hackerpreneur

**Comment by jkresner** [comment]
Hopefully it's ok to wait until tomorrow. This is gonna be a mega deploy. Very excited!!

**Comment by jkresner** [comment]
Should be fine now. Want to have another crack?

On Tuesday, January 26, 2016, Jonathon Kresner jk@airpair.com wrote:

> Another rather large update coming in the next few hours.
> 
> On Tuesday, January 26, 2016, Paul McGuire <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > I have prepared a tutorial article on Pyparsing, and have added tags and
> > supporting info However, I seem to be stuck when trying to SUBMIT this
> > article I have attached a screenshot at the point at which I am stuck I
> > have tried with Firefox, Chrome, and Microsoft Edge, all with the same
> > result
> > 
> > The problem seems to be in the creation of my github repo, as I never get
> > a response that the article slug is no longer available
> > 
> > The URL is https://authorairpaircom/submit/54ff547ae02a350c00dab9a8
> > [image: airpair_screenshot2]
> > https://camo.githubusercontent.com/ae340c43fabb35c584bc62e2966fb3dc2ec063ce/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f3338333837352f31323538343736362f61333465383735342d633430652d313165352d396338352d6235666238623930633232326a7067
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/airpair/author.airpair.com/issues/2.
> 
> ## 
> 
> _Jonathon Kresner_
> _Co-founder, CEO_
> @AirPair http://twitter.com/airpair | _airpair.com
> http://www.airpair.com_
> @hackerpreneur http://twitter.com/hackerpreneur

## 

_Jonathon Kresner_
_Co-founder, CEO_
@AirPair http://twitter.com/airpair | _airpair.com
http://www.airpair.com_
@hackerpreneur http://twitter.com/hackerpreneur
