### ISSUE TITLE
[0.6.5-beta.2] Access to author.airpair for GitHub account [20084381:emilyjohns] by request to team@airpair.com

### ISSUE THREAD

**Issue by emilyjohns** [airpair/author.airpair.com#8]
Why I can not login to airpair.com with my github account.

**Comment by jkresner** [comment]
Because you look like SPAM.

**Comment by emilyjohns** [comment]
NO, I am not spamming, What can I do to access  airpair.com

**Comment by jkresner** [comment]
What's are you blocked from doing?
